name: cupertino_clock
description: An analog clock that looks and feels the same as iPhone's analog clock from Standby Mode.
version: 0.1.0+1
repository: https://github.com/tomassasovsky/cupertino_clock.git
homepage: https://github.com/tomassasovsky/cupertino_clock

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  async: ^2.11.0
  flutter:
    sdk: flutter
  meta: ^1.15.0
  timezone: ^0.9.3

dev_dependencies:
  fake_async: ^1.3.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  fonts:
    - family: San Francisco
      fonts:
        - asset: fonts/SFProText-Regular.ttf
        - asset: fonts/SFProText-RegularItalic.ttf
          style: italic
        - asset: fonts/SFProText-Bold.ttf
          weight: 700
        - asset: fonts/SFProText-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/SFProText-Semibold.ttf
          weight: 600
        - asset: fonts/SFProText-SemiboldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/SFProText-Medium.ttf
          weight: 500
        - asset: fonts/SFProText-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/SFProText-Light.ttf
          weight: 300
        - asset: fonts/SFProText-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/SFProText-Heavy.ttf
          weight: 800
        - asset: fonts/SFProText-HeavyItalic.ttf
          weight: 800
          style: italic
